config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "dashboard", to: "pages#dashboard"
  get "dashboardwish", to: "pages#dashboardwish"
  resources :wishlists

  resources :wishlists_gifts, only: [:show]
  resources :votes, only: [:create]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

end

app/views/shared/_avatar.html.erb
<div id="user-<%=user.id%>">
            <%= image_tag user.photo, class:"avatar-rond"%> <p class="show-votes"><%= user.votes.where(wishlists_gift_id: wishlist.wishlists_gifts.pluck(:id)).count %> Votes</p>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
        <%= image_tag "avatar/logo.png", id: "logo-navbar-green" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-link3">
            <%= link_to "Mes wishlists", dashboardwish_path, class: "nav-link3" %>
          </li>
          <li class="nav-item">
            <%= link_to "Mon profil", dashboard_path, class: "nav-link4" %>
          </li>
          <li class="nav-item dropdown">
              <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, crop: :fill, class: "avatar1 dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% else %>
              <%= image_tag "avatar/avatar_vide", class: "avatar dropdown-toggle" %>
              <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Se déconnecter", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "S'inscrire", new_user_session_path, class: "nav-link1" %>
          </li>
          <li class="nav-item">
            <%= link_to "Se connecter", new_user_session_path, class: "nav-link2" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbargreen.html.erb
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container-fluid">
      <%= link_to "/", class: "navbar-brand" do %>
        <%= image_tag "avatar/logo.png", id: "logo-navbar-green" %>
      <% end %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto blanc">
          <% if user_signed_in? %>
            <li class="nav-item active-blanc">
              <%= link_to "Mes wishlists", dashboardwish_path, class: "nav-link-wishlist-blanc" %>
            </li>
            <li class="nav-item-mesvotes-blanc">
              <%= link_to "Mon profil", dashboard_path, class: "nav-link-votes-blanc" %>
            </li>
            <li class="nav-item dropdown">
              <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% else %>
              <%= image_tag "avatar/avatar_vide", class: "avatar dropdown-toggle" %>
              <% end %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Se déconnecter", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "S'inscrire", new_user_session_path, class: "nav-link-btn" %>
            </li>
            <li class="nav-item">
              <%= link_to "Se connecter", new_user_session_path, class: "nav-link-blanc" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

app/views/shared/_navbargreenwhite.html.erb
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto blanc">
          <% if user_signed_in? %>
            <li class="nav-item active-blanc">
              <%= link_to "Mes wishlists", dashboardwish_path, class: "nav-link-wishlist-blanc" %>
            </li>
            <li class="nav-item-mesvotes-blanc">
              <%= link_to "Mon profil", dashboard_path, class: "nav-link-votes-blanc" %>
            </li>
            <li class="nav-item dropdown">
              <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% else %>
              <%= image_tag "avatar/avatar_vide", class: "avatar dropdown-toggle" %>
              <% end %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Se déconnecter", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "S'inscrire", new_user_session_path, class: "nav-link-btn" %>
            </li>
            <li class="nav-item">
              <%= link_to "Se connecter", new_user_session_path, class: "nav-link-blanc" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>