config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "dashboard", to: "pages#dashboard"
  get "dashboardwish", to: "pages#dashboardwish"
  resources :wishlists

  resources :wishlists_gifts, only: [:show]
  resources :votes, only: [:create]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

end

app/views/pages/dashboard.html.erb
 <%= render "shared/navbar" %>




<div class="dash-king">

  <!-- dashboard -->
  <div data-controller="dashboard" class="dashboard">
    <!-- 3 logo a gauche -->
    <div class="dashboard-nav ">
      <div class="dashboard-logo-vide">



      </div>

      <div class="dashboard-logo fixed-bottom">

        <div class="dash-img-1" data-action="click->dashboard#update1">
          <%= image_tag "icones/poussin.png", class:"dash-avatar-rond"%>
        </div>
        <p>mon profil</p>


        <div class="dash-img-2" data-action="click->dashboard#update2">
          <%= image_tag "icones/feux-dartifice.png", class:"dash-avatar-rond dash-push"%>
        </div>
        <p>mes wishlists</p>


        <%= image_tag "grafitis/click.svg", class:"dash-avatar-click"%>
        <%= image_tag "grafitis/pointer.svg", class:"dash-avatar-pointer"%>



      </div>
    </div>

    <div class="dashboard-page">
      <div class="dash-backgvert fixed-bottom">
        <%= image_tag "image-bottom-vert.png", class:"stickybggreenbra " %>
      </div>


      <!-- premiere page(mon profil) -->
      <div class="dashboard-mon-profil" data-dashboard-target="premierepage">
        <!-- IMG -->
        <%= image_tag "fonddashprofil.png", class:"fonddashprofil"%>
      <!--supp classs none et mettre <div class="dashboard-mon-profil"> -->
        <div class="dashboard-title">
          <h2>Mon profil</h2>
        </div>

        <div class="dash-big-image-profil">
          <%#= image_tag "https://images.unsplash.com/photo-1574466853640-8557d3e4ab2c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2340&q=80", class: "avatar-dash", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, crop: :fill, class: "avatar-dash" %>
            <% else %>
            <%= image_tag "avatar/avatar_vide", class: "avatar-dash" %>
            <% end %>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Se déconnecter", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
          </div>

        </div>


        <div class="dashboard-quatre1">

          <div class="dashboard-deux">

            <p class="greypil"><%= current_user.prenom %></p>

            <p class="greypil"><%= current_user.nom %></p>

          </div>

          <div class="dashboard-deux">

            <p class="greypil"><%= current_user.email %></p>

            <div class="greypil-count-profil">
              <p class="nombre-de-wishlist">Nombre de Wishlist: <%= @my_wishlists.count %><%= image_tag "grafitis/wishlist.svg", class:"dash-dash" %> </p>
              <p class="nombre-de-vote"><%= image_tag "grafitis/coeur.svg", class:"dash-coeur" %>Nombre de Votes: <%= @current_user_votes.count %></p>
            </div>

          </div>

        </div>
          <!-- <%= image_tag "avatar/Dorian.jpeg", class:"avatar-rond"%> -->


      </div>


      <!-- deuxieme page(mes wishlist) -->
      <div class="dashboard-mes-wishlists d-none" data-dashboard-target="deuxiemepage">
        <!-- <div class="dashboarddnone"> -->
      <!--supp classs none et mettre <div class="dashboard-mes-wishlists"> -->

        <%= image_tag "etoiles/star-2.png", class:"dash-star-1"%>
        <%= image_tag "etoiles/star-7.png", class:"dash-star-2"%>
        <%= image_tag "etoiles/star-4.png", class:"dash-star-3"%>
        <%= image_tag "etoiles/star-4.png", class:"dash-star-4"%>
        <%= image_tag "etoiles/star-1.png", class:"dash-star-5"%>

        <%= image_tag "etoiles/star-7.png", class:"dash-star-6"%>
        <%= image_tag "etoiles/star-7.png", class:"dash-star-7"%>
        <%= image_tag "etoiles/star-4.png", class:"dash-star-8"%>
        <%= image_tag "etoiles/star-8.png", class:"dash-star-9"%>
        <%= image_tag "etoiles/star-9.png", class:"dash-star-10"%>



        <div class="dashboard-title-w">
          <h2>Mes wishlists</h2>


        </div>
        <%= image_tag "grafitis/trait-g", class:"trait-mes-wish" %>

        <div class="dashboard-all-wishlist-and-all-team">


          <% @my_wishlists.each do |wishlist| %>
              <div class="dashboard-one-wishlist-and-one-team">

                <%= image_tag "grafitis/top", class: "imgcup" %>
                <%= image_tag "grafitis/undraw_flower", class: "imgflower" %>




                <div class="dash-cadeau">
                  <% top_gift = wishlist.wishlists_gifts.top_votes_for_wishlist_gift(wishlist.id) %>
                  <% if top_gift.present? %>
                    <p>Le cadeau le plus voté</p>

                    <%= image_tag(top_gift.gift.photo) %>
                    <p><%= top_gift.gift.name %></p>
                  <% else %>
                    <p>Aucun cadeau n'a encore été voté pour cette wishlist</p>
                  <% end %>
                </div>

                <div class="dashboard-all-wishlist">
                  <%= link_to wishlist.name , wishlist_path(wishlist), class: "dashboard-1-wishlist greypil"%>
                </div>

                <div class="dash-team">
                  <% User.joins(:votes).where(votes: { wishlists_gift_id: wishlist.wishlists_gifts.pluck(:id) }).uniq.each do |user| %>


                        <%= image_tag user.photo, class: "avatar-dash-team" %>

                  <% end %>
                </div>



              </div>





          <% end %>
        </div>
      </div>


      <!-- troisieme page(mes wishlists) -->
      <div class="dashboard-mon-top-cadeau d-none"  data-dashboard-target="troisiemepage">

        <div class="dashboard-title-top">
          <h2>Top cadeau</h2>
        </div>

        <div class="top-bas">
          <div class="top-gauche">
            <div class="top-img">
              <%= image_tag "icones/poussin.png"%>
            </div>
          </div>

          <div class="top-droite">

            <div class="top-votes">
              <h3>Votess</h3>
            </div>


            <div class="top-p">
              <p>le paragraphe blablabla blabla blablabal blablabl blablablablable paragraphe blablabla blabla blablabal blablabl blablablablable paragraphe blablabla blabla blablabal blablabl blablablablable paragraphe blablabla blabla blablabal blablabl blablablablabl</p>
            </div>

          </div>
        </div>

      </div>
    </div>

  </div>
</div>

app/views/pages/dashboardwish.html.erb
  <%= render "shared/navbar" %>




<div class="dash-king">

  <!-- dashboard -->
  <div data-controller="dashboard" class="dashboard">
    <!-- 3 logo a gauche -->
    <div class="dashboard-nav ">
      <div class="dashboard-logo-vide">



      </div>

      <div class="dashboard-logo fixed-bottom">

        <div class="dash-img-1" data-action="click->dashboard#update1">
          <%= image_tag "icones/poussin.png", class:"dash-avatar-rond"%>
        </div>
        <p>mon profil</p>


        <div class="dash-img-2" data-action="click->dashboard#update2">
          <%= image_tag "icones/feux-dartifice.png", class:"dash-avatar-rond dash-push"%>
        </div>
        <p>mes wishlists</p>


        <%= image_tag "grafitis/click.svg", class:"dash-avatar-click"%>
        <%= image_tag "grafitis/pointer.svg", class:"dash-avatar-pointer"%>



      </div>
    </div>

    <div class="dashboard-page">
      <div class="dash-backgvert fixed-bottom">
        <%= image_tag "image-bottom-vert.png", class:"stickybggreenbra " %>
      </div>


      <!-- premiere page(mon profil) -->
      <div class="dashboard-mon-profil d-none" data-dashboard-target="premierepage">
        <!-- IMG -->
        <%= image_tag "fonddashprofil.png", class:"fonddashprofil"%>
      <!--supp classs none et mettre <div class="dashboard-mon-profil"> -->
        <div class="dashboard-title">
          <h2>Mon profil</h2>
        </div>

        <div class="dash-big-image-profil">
          <%#= image_tag "https://images.unsplash.com/photo-1574466853640-8557d3e4ab2c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2340&q=80", class: "avatar-dash", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, crop: :fill, class: "avatar-dash" %>
            <% else %>
            <%= image_tag "avatar/avatar_vide", class: "avatar-dash" %>
            <% end %>

        </div>


        <div class="dashboard-quatre1">

          <div class="dashboard-deux">

            <p class="greypil"><%= current_user.prenom %></p>

            <p class="greypil"><%= current_user.nom %></p>

          </div>

          <div class="dashboard-deux">

            <p class="greypil"><%= current_user.email %></p>

            <div class="greypil-count-profil">
              <p class="nombre-de-wishlist">Nombre de Wishlist: <%= @my_wishlists.count %><%= image_tag "grafitis/wishlist.svg", class:"dash-dash" %> </p>
              <p class="nombre-de-vote"><%= image_tag "grafitis/coeur.svg", class:"dash-coeur" %>Nombre de Votes: <%= @current_user_votes.count %></p>
            </div>

          </div>

        </div>
          <!-- <%= image_tag "avatar/Dorian.jpeg", class:"avatar-rond"%> -->


      </div>


      <!-- deuxieme page(mes wishlist) -->
      <div class="dashboard-mes-wishlists" data-dashboard-target="deuxiemepage">
        <!-- <div class="dashboarddnone"> -->
      <!--supp classs none et mettre <div class="dashboard-mes-wishlists"> -->

        <%= image_tag "etoiles/star-2.png", class:"dash-star-1"%>
        <%= image_tag "etoiles/star-7.png", class:"dash-star-2"%>
        <%= image_tag "etoiles/star-4.png", class:"dash-star-3"%>
        <%= image_tag "etoiles/star-4.png", class:"dash-star-4"%>
        <%= image_tag "etoiles/star-1.png", class:"dash-star-5"%>

        <%= image_tag "etoiles/star-7.png", class:"dash-star-6"%>
        <%= image_tag "etoiles/star-7.png", class:"dash-star-7"%>
        <%= image_tag "etoiles/star-4.png", class:"dash-star-8"%>
        <%= image_tag "etoiles/star-8.png", class:"dash-star-9"%>
        <%= image_tag "etoiles/star-9.png", class:"dash-star-10"%>



        <div class="dashboard-title-w">
          <h2>Mes wishlists</h2>


        </div>
        <%= image_tag "grafitis/trait-g", class:"trait-mes-wish" %>

        <div class="dashboard-all-wishlist-and-all-team">


          <% @my_wishlists.each do |wishlist| %>
              <div class="dashboard-one-wishlist-and-one-team">

                <%= image_tag "grafitis/top", class: "imgcup" %>
                <%= image_tag "grafitis/undraw_flower", class: "imgflower" %>




                <div class="dash-cadeau">
                  <% top_gift = wishlist.wishlists_gifts.top_votes_for_wishlist_gift(wishlist.id) %>
                  <% if top_gift.present? %>
                    <p>Le cadeau le plus voté</p>

                    <%= image_tag(top_gift.gift.photo) %>
                    <p><%= top_gift.gift.name %></p>
                  <% else %>
                    <p>Aucun cadeau n'a encore été voté pour cette wishlist</p>
                  <% end %>
                </div>

                <div class="dashboard-all-wishlist">
                  <%= link_to wishlist.name , wishlist_path(wishlist), class: "dashboard-1-wishlist greypil"%>
                </div>

                <div class="dash-team">
                  <% User.joins(:votes).where(votes: { wishlists_gift_id: wishlist.wishlists_gifts.pluck(:id) }).uniq.each do |user| %>


                        <%= image_tag user.photo, class: "avatar-dash-team" %>

                  <% end %>
                </div>



              </div>





          <% end %>
        </div>
      </div>


      <!-- troisieme page(mes wishlists) -->
      <div class="dashboard-mon-top-cadeau d-none"  data-dashboard-target="troisiemepage">

        <div class="dashboard-title-top">
          <h2>Top cadeau</h2>
        </div>

        <div class="top-bas">
          <div class="top-gauche">
            <div class="top-img">
              <%= image_tag "icones/poussin.png"%>
            </div>
          </div>

          <div class="top-droite">

            <div class="top-votes">
              <h3>Votess</h3>
            </div>


            <div class="top-p">
              <p>le paragraphe blablabla blabla blablabal blablabl blablablablable paragraphe blablabla blabla blablabal blablabl blablablablable paragraphe blablabla blabla blablabal blablabl blablablablable paragraphe blablabla blabla blablabal blablabl blablablablabl</p>
            </div>

          </div>
        </div>

      </div>
    </div>

  </div>
</div>

app/views/pages/home.html.erb
 <div class="home-body">

 <!--------------------------NAVBAR---------------------------------->

 <%= render "shared/navbargreen" %>


 <!--------------------------END NAVBAR---------------------------------->



 <!--------------------------TOP---------------------------------->

<div class="container">

<!---Title Hero banner à gauche---->

  <section class="hero-banner-top">

    <div class="Text-hero-banner">
      <h1 class="titre home">
          Trouve LE cadeau rapidement et facilement !
      </h1>
      <p class="text-home">
          Choisis tes critères, rassemble tes amis et vote pour le meilleur cadeau de la liste.
          C'est simple, rapide et ludique.
      </p>
        <%= link_to "Découvrir", new_wishlist_path, class:"button-home" %>
    </div>

 <!---END Title Hero banner à gauche---->


 <!---IMG Hero banner à droite---->

      <div class="image-hero-banner">
        <%=image_tag "cadeau-img-banner.jpg"%>
      </div>

  </section>

 <!---END IMG Hero banner à droite---->


 <!--------------------------BOTTOM---------------------------------->

  <section class="hero-banner-bottom">

 <!--- Fleche et numéro à gauche bottom ---->

        <%=image_tag "fleche et images", class:"fleche-numero"%>


 <!--- END Fleche et numéro à gauche bottom ---->


 <!--- Paragraphe droite bottom ---->


    <div class="Paragraphes">
      <p class="titre-para"><strong>Un cadeau...</strong></p>
      <p class="text-para">
        Lorsqu'il s'agit de choisir un cadeau ou une activité à offrir à quelqu'un, il est important de se poser trois questions essentielles : <strong>"Pour quelle occasion ?", "Pour qui ?" et "Quels sont ses centres d'intérêts ?".</strong> En répondant à ces questions, vous pourrez trouver le cadeau ou l'activité idéale pour la personne en question.
      </p>
      <p class="titre-para"><strong>...pour offrir...</strong></p>
      <p class="text-para">
        <strong>"Quel est le budget ?" et "Qui participe ?"</strong> sont aussi des questions importantes afin de ne pas dépasser vos moyens financiers. En connaissant le budget, vous pourrez alors choisir une option qui convient le mieux à tous !
      </p>
      <p class="titre-para"><strong>...ensemble !</strong></p>
      <p class="text-para">
        Votez pour le cadeau qui vous semble parfait et offrez un présent inoubliable. <strong>Vous allez faire des heureux !</strong>
        Vous pouvez dès à présent créer votre première wishlist et inviter vos amis :
      </p>
    </div>

  </section>


    <div class="btn-bottom">
      <%= link_to "Découvrir", new_wishlist_path, class:"button-home" %>
    </div>
    <%= image_tag "image-bottom-vert", id:"home-bottom-image"%>
 <!--- END Paragraphe droite bottom ---->

</div>


</div>