config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "dashboard", to: "pages#dashboard"
  get "dashboardwish", to: "pages#dashboardwish"
  resources :wishlists

  resources :wishlists_gifts, only: [:show]
  resources :votes, only: [:create]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user
  has_many :tags, through: :wishlists_tag
  has_many :wishlists_gifts, dependent: :destroy
  has_many :gifts, through: :wishlists_gifts
  has_many :wishlists_tags, dependent: :destroy
  has_many :tags, through: :wishlists_tags
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  def index
    @wishlists = policy_scope(Wishlist)
  end

  def show
    @wishlist = Wishlist.find(params[:id])
    # filter les gifts en fonction des tags # récupérer la valeur du champ de saisie
    @tags = @wishlist.tags
    # @gifts = []
    # WishlistsGift.where(wishlist: @wishlist).each do |wishlistgift|
    #   @gifts << Gift.find(wishlistgift.gift_id)
    # end
    # @max_draw = Drawing.where("drawing_number ~* ?", '^A\d{4}$')



    # --------je trie les tags par ordre alphab ------------
    # --------je garde seulement le 1er ------------
    # --------car il commence par 0, 1, 2 ou 5 ------------
    # --------donc c'est le tag du prix ------------
    @tag_price = @tags.sort_by{|tag| tag.name}.first

    # --------on recupère le prix min et max du range ------------
    @min_price = @tag_price.name.match(/\A.*\./).to_s.split(".")[0].to_i
    @max_price = @tag_price.name.match(/\...\w*/).to_s.split(".").last.to_i

    # --------on garde seulement les cadeaux inclus dans ce range ------------
    @wish_gifts = @wishlist.wishlists_gifts.select do |w_gift|
      w_gift.gift.price > @min_price && w_gift.gift.price < @max_price
    end

    # --------on les trie en fonction du nb  de votes ------------
    @gifts = @wish_gifts.sort_by {|w_g| w_g.vote}.reverse



    # --------SOLUTION JORDANE SI BESOIN ------------
    # @gifts = @wishlist.wishlists_gifts.order(vote: :DESC)



    # @gifts = Gift.all.select { |gift| gift.tags.include?(@tags) }
    #@gifts = Gift.joins(:tags).where(tags: { id: @tags.pluck(:id) }).distinct
    # Gift.joins(:tags) : Cette partie de la ligne de code effectue une jointure entre les tables gifts et tags. En utilisant joins, nous demandons à ActiveRecord d'effectuer une jointure interne entre les tables en fonction de leur relation, ce qui signifie que seuls les cadeaux ayant au moins un tag seront inclus dans la requête.
    # Nous utilisons :tags pour spécifier la relation entre les modèles Gift et Tag. where(tags: { id: @tags.pluck(:id) }) : Cette partie de la ligne de code applique un filtre à la requête en utilisant les ID des tags de la variable @tags. Nous utilisons pluck(:id) pour extraire un tableau contenant les ID des tags, puis nous construisons une condition de filtre en utilisant ces ID. Nous spécifions la table tags et l'attribut id dans la condition en utilisant tags: { id: ... }
    # distinct : Cette partie de la ligne de code supprime les doublons de la requête. Si un cadeau a plusieurs tags correspondant aux ID filtrés, il apparaîtra une fois dans la collection @gifts
    # En résumé, la nouvelle ligne de code sélectionne tous les cadeaux qui ont au moins un tag correspondant aux tags de la variable @tags, en utilisant une jointure entre les tables gifts et tags. Elle applique également une condition de filtre pour ne sélectionner que les cadeaux qui ont des tags spécifiques. Enfin, elle supprime les doublons de la requête pour s'assurer que chaque cadeau n'apparaît qu'une fois dans la collection @gifts
    authorize @wishlist
  end

  def new
    @wishlist = Wishlist.new

    @first_tag = Tag.all.select { |tag| tag.name == "Anniversaire" || tag.name == "Noël" || tag.name == "Naissance" || tag.name == "Petit cadeau" }
    # first_tag = selectionne dans tout les tags, les tags ou le tag est == a ....
    @second_tag = Tag.all.select { |tag| tag.name == "Bébé" || tag.name == "Ado" || tag.name == "Adulte" || tag.name == "Enfant" }

    @third_tag = Tag.all.select { |tag| tag.name == "Décoration" || tag.name == "Sport" || tag.name == "Made in France" || tag.name == "Lifestyle" || tag.name == "Beauté" || tag.name == "Zéro déchet" || tag.name == "Artisanal" || tag.name == "DIY" || tag.name == "High-Tech"}

     @fourth_tag = Tag.all.select { |tag| tag.name == "0...500€" || tag.name == "0...25€" || tag.name == "25...50€" || tag.name == "50...100€" || tag.name == "100...200€" || tag.name == "200...500€" }

    authorize @wishlist
  end

  def create
    @wishlist = Wishlist.new
    @wishlist.user = current_user

    @wishlist.name = params[:wishlist_name]
    # assignation wishlist.name au params dans le formulaire de depars
    # <%= label_tag :wishlist_name, "Nom de la wishlist"%>
    #  <%= text_field_tag :wishlist_name %>
    # wishlist > new.html.erb
    @wishlist.save
    # recuperer ;es tags en true dans le formualire les trsnformer en wishlist tag et les dpnner a la wishlist
    @chosen_tag = params.select { |key, value| value == "true" }.keys
    @chosen_tag.each do |tag|
      WishlistsTag.create!(wishlist: @wishlist, tag: Tag.find_by_name(tag))
    end

    @tags = @wishlist.tags
    @gifts = Gift.joins(:tags).where(tags: { id: @tags.pluck(:id) }).distinct
    @gifts.each do |gift|
      WishlistsGift.create(wishlist: @wishlist, gift: gift, vote: 0)
    end

    authorize @wishlist
    @wishlist.save
    redirect_to wishlist_path(@wishlist)
  end

  def edit
    @wishlist = Wishlist.find(params[:id])
    authorize @wishlist
  end

  def destroy
    @wishlist = Wishlist.find(params[:id])
    authorize @wishlist
    @wishlist.destroy
  end

end

private

def wishlist_params
  params.require(:wishlist).permit(:name)
end

app/views/wishlists/index.html.erb
<h1>wishlist</h1>


<% @wishlists.each do |wishlist| %>
  <p><%= link_to wishlist.name , wishlist_path(wishlist) %></p>
<% end %>

app/views/wishlists/new.html.erb
 <%= render "shared/navbar" %>

<%# </--------- partie 1 des questions EVENT ---------------> %>
<div data-controller= "tag-selection">

  <%# formulaire  %>
  <%= form_tag wishlists_path do %>
  <div class="container">
    <div data-tag-selection-target="first" class="div-question">
      <div class="card-grid">
        <% @first_tag.each do |tag| %>
          <div data-action= "click->tag-selection#firstcheck"><%= check_box_tag tag.name, true, false, class: 'd-done'%>
            <div class="card-tag"><%= tag.name %>
              <% if @first_tag.index(tag) == 1 %>
                <%= image_tag "grafitis/trait-y", class: "top-left-icon" %>
              <% end %>
              <% if @first_tag.index(tag) == 2 %>
                <%= image_tag "grafitis/trait-c", class: "top-right-icon" %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="questions">
        <p>Pour quelle occasion cherchez-vous un cadeau ? </p>
      </div>
      <%= image_tag "grafitis/bas", id:"home-bottom-image-category"%>
    </div>
  </div>

<%# </--------- partie 2 des questions AGE---------------> %>
  <div class="container">
    <div data-tag-selection-target="second" class="d-none">
      <div class="div-question">
        <div class="questions">
          <p>Qui sera l'heureux élu ? </p>
          <%= image_tag "grafitis/fleche", class: "left-fleche" %>
        </div>
        <div class="card-grid-2">
          <% @second_tag.each do |tag| %>
            <div data-action= "click->tag-selection#secondcheck" class="card-tag-2"><%= tag.name %>
                <%= check_box_tag tag.name, true, false, class: 'd-none'%>
              <% if @second_tag.index(tag) == 2 %>
                <%= image_tag "grafitis/trait", class: "bottom-right-icon" %>
              <% end %>
            </div>
          <% end %>
        </div>
        <%= image_tag "grafitis/bas-rev", id:"home-bottom-image-category-rev"%>
      </div>
    </div>
  </div>
<%# </--------- partie 3 des questions TAGS---------------> %>
<div class="container">
  <div data-tag-selection-target="third" class="d-none">
    <div class="div-question-9">
      <div class="card-grid-9">
        <% @third_tag.each do |tag| %>
          <div data-action= "click->tag-selection#thirdcheck", class="card-tag-9">
            <%= check_box_tag tag.name, true, false, class: 'd-none'%>
            <%= image_tag tag.image_path, class: "new--icones"%><%= tag.name %>
            <% if @third_tag.index(tag) == 2 %>
                <%= image_tag "grafitis/trait-e", class: "graf-chien" %>
                <%= image_tag "grafitis/trait-c", class: "graf-tour" %>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="questions-9">
        <p>Quels sont ses centres d'interêts ? </p>
        <%= image_tag "grafitis/trait-f", class: "right-trait" %>
      </div>
    </div>
    <div class="btn-suivant">
    <p data-action= "click->tag-selection#thirdbuttoncheck" data-tag-selection-target="thirdbutton"  class="d-none">ok !</p>
      </div>
      <%= image_tag "grafitis/bas", id:"home-bottom-image-category"%>
  </div>
</div>
<%# </--------- partie 4 des questions BUDGET---------------> %>

<div class="container">
  <div data-tag-selection-target="fourth" class="d-none">
    <div class="div-question-6">
      <div class="questions-6">
        <p>Quel est votre budget ? </p>
          <%= image_tag "grafitis/trait", class: "budget" %>
      </div>
      <div class="card-grid-6">
        <% @fourth_tag.each do |tag| %>
          <div data-action= "click->tag-selection#fourthcheck" class="card-tag-9"><%= check_box_tag tag.name, true, false, class: 'bestdnone'%>
            <%= tag.name %>
              <% if @fourth_tag.index(tag) == 2 %>
                <%= image_tag "grafitis/trait-c", class: "budget-trait" %>
              <% end %>
          </div>
        <% end %>
      </div>
      <%= image_tag "grafitis/bas-rev", id:"home-bottom-image-category-rev"%>
    </div>
  </div>
</div>

<%# </--------- partie 5 des questions NOM---------------> %>
<div class="container">
    <div data-tag-selection-target="five" class="d-none wishlist-en-cours">
      <%= label_tag :wishlist_name, "Nouvelle wishlist en cours ..."%>
        <div class="ecrire">
          <%= text_field_tag :wishlist_name%>
        </div>
          <%= submit_tag "Créer !", class: "btn-creation"%>
          <%= image_tag "etoiles/full-star", id:"full-star"%>
    </div>
  <% end %>
</div>

<%# </--------- range des prix ---------------> %>

  <div class="range_container d-none" data-action="mousemove->tag-selection#changerange">
    <div class="sliders_control">
        <input id="fromSlider" type="range" value="20" min="0" max="300"/>
        <input id="toSlider" type="range" value="60" min="0" max="300"/>
    </div>
    <div class="form_control">
        <div class="form_control_container">
            <!-- on met le notre nouveau resultat min basé sur rangeinput min qui est plus bas  -->
            <p data-tag-selection-target="rangeresultmin"></p>
            <div class="form_control_container__time">Min</div>
            <!-- rangeinput min moche de base  -->
            <input class="form_control_container__time__input d-none" type="number" id="fromInput" value="20" min="0" max="300" data-tag-selection-target="rangeinputmin"/>
        </div>
        <div class="form_control_container">
            <p data-tag-selection-target="rangeresultmax"></p>
            <div class="form_control_container__time">Max</div>
            <input class="form_control_container__time__input d-none" type="number" id="toInput" value="60" min="0" max="300" data-tag-selection-target="rangeinputmax"/>
        </div>
    </div>
  </div>


</div>

app/views/wishlists/show.html.erb
 <!-- app/views/offers/show.html.erb -->
<% content_for :meta_title, "#{@wishlist.name} is on #{DEFAULT_META["Findo"]}" %>

 <div class="home-body">


 <!--------------------------NAVBAR---------------------------------->


 <%= render "shared/navbargreen" %>

 <!--------------------------END NAVBAR---------------------------------->




 <!--------------------------TOP---------------------------------->

<!---Title & tag wishlist---->

  <div class="wishlist-name-description" data-controller="wishlist-subscription"
  data-wishlist-subscription-wishlist-id-value="<%= @wishlist.id %>">

    <div class="Text-wishlist-name">
      <h1 class="titre">
          <%= @wishlist.name %>
      </h1>


      <p class="text">
          Vote pour le cadeau qui correspond le mieux à la personne !
      </p>
      <div data-controller="share" data-share-url-value="<%=wishlist_url(@wishlist)%>">
        <button class="btn-share" data-action="click->share#share"> Partager</button>
      </div>
    </div>
  </div>


    <div class="card pillule">
      <% @wishlist.wishlists_tags.each do |tag| %>
        <% if !tag.tag.image_path.nil? %>
          <p class="card-tag-9"><%= image_tag tag.tag.image_path, class: "new--icones"%><%= tag.tag.name %></p>
        <% else %>
          <p class="card-tag-9"><%= tag.tag.name %></p>
        <% end %>
      <% end %>
    </div>





 <!---END Title @ tag wishlist---->


 <!--------------------------BOTTOM---------------------------------->


<div class="avatar-cards">


 <!--- Avatard gauche ---->
  <div class="avatar-section">
    <div class="vote-avatar">

    <% User.joins(votes: { wishlists_gift: :wishlist }).where(wishlists: { id: @wishlist.id }).distinct.each do |user| %>
      <% if user.votes.exists?(wishlists_gift_id: @wishlist.wishlists_gifts.pluck(:id)) %>
        <%= render "shared/avatar", user: user, wishlist: @wishlist %>

      <% end %>
    <% end %>
    </div>
 </div>







 <!--- END Avatard gauche ---->



 <!--- Cards droite---->
    <div class="cards" data-controller="upvote">
        <% @gifts.each do |wishlists_gift| %>
          <div class="animated-card">
            <div class="front-card d-flex justify-content-end" style="background-image: url(<%= wishlists_gift.gift.photo %>)">
              <div class="p-2">
                <p id="vote-<%=wishlists_gift.id%>", class="rank"><%= wishlists_gift.vote%></p>
              </div>
              <%#= cl_image_tag wishlists_gift.gift.photo, height: 150, width: 200 , crop: :fill,class:"" %>
            </div>

            <div class="back-card">
              <div class="back-card-info">
                <%= image_tag "icones/oeil.png", class:"oeil" %>
                <%# <h2>mettre l'oeil</h2> %>
                <div class="data">
                  <h3><%= wishlists_gift.gift.name %></h3>
                  <h3><%= wishlists_gift.gift.price %>€</h3>
                </div>
                <div class="terminus">
                   <%= link_to "Détails" , wishlists_gift_path(wishlists_gift), class: "button-home variant1" %>
      <%#Dans le model Vote, on va checker s'il y a un wishlists_gift_id et un user_id. S'il y en a, tu prends le wishlists_gift_id donc l'id de ta wishlist et l'id du current user, puis tu regardes si son vote est inférieur à 1. Si oui tu lui laisse le btn pour voter. Sinon le btn est supprimé %>
                   <% if Vote.where('wishlists_gift_id=? and user_id=?', wishlists_gift.id, current_user.id).size < 1  %>
                    <p class= "button-home variant2" data-action="click->upvote#addvote" data-wishlistgift=<%= wishlists_gift.id%>>Voter</p>
                   <% end %>
                </div>
              </div>

            </div>
          </div>
        <% end %>
    </div>
</div>

<!--- END Cards droite---->


</div>